Spi
sp-bechara/Floor1_training pull request #7
Opened 2023-06-20 09:02 UTC by sp-bechara

2023-06-27 12:03 UTC, kaushaleinfo requested changes

2023-06-27 12:03 UTC, kaushaleinfo commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +//uint8_t readRx[261];
Put this inside debug_SPI_Flash macro

2023-06-27 12:03 UTC, kaushaleinfo commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +			HAL_UART_Transmit(&huart2, (uint8_t *)"Device is ready\n", sizeof("Device is ready\n"), 1000);
Put this inside debug_SPI_Flash macro

2023-06-27 12:03 UTC, kaushaleinfo commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +			break;
Put this break appropriate space

2023-06-27 12:03 UTC, kaushaleinfo commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +{
Put vaild address check

2023-06-27 12:03 UTC, kaushaleinfo commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +        //Read data from buffer
Put this inside debug_SPI_Flash macro

2023-06-27 12:03 UTC, kaushaleinfo commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +        deviceReady();
Put this function at appropriate location

2023-06-27 12:03 UTC, kaushaleinfo commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +        readRangeCheck=(readRange >= 256) ? 261 :readRange+7;
what is 256 and 261 ?

2023-06-27 12:42 UTC, sp-bechara commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +//uint8_t readRx[261];
done

2023-06-27 12:42 UTC, sp-bechara commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +			HAL_UART_Transmit(&huart2, (uint8_t *)"Device is ready\n", sizeof("Device is ready\n"), 1000);
done

2023-06-27 12:43 UTC, sp-bechara commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +			break;
done

2023-06-27 12:44 UTC, sp-bechara commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +        //Read data from buffer
As discussed, we don't need to do it anymore...As only print inside it is only kept under debug macro.

2023-06-27 12:44 UTC, sp-bechara commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +        deviceReady();
done

2023-06-28 04:36 UTC, sp-bechara commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +        readRangeCheck=(readRange >= 256) ? 261 :readRange+7;
done

2023-06-28 05:06 UTC, sp-bechara commented on Task/MCU/Floor1_USART_inputdata/Core/Src/main.c
> +{
done

2023-07-03 10:16 UTC, kaushaleinfo approved these changes

2023-07-03 10:19 UTC, merged